purbeurre_project/bestproduct/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "bestproduct"

urlpatterns = [
    path('', views.index, name='index'),
    path('replace/', views.replace, name='replace'),
    path('detail/<str:product_id>/', views.detail, name='detail'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('favorite/', views.favorite, name='favorite'),
    path('login/', auth_views.LoginView.as_view(
         template_name='bestproduct/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(
         template_name='bestproduct/logout.html'),
         name='logout'),
    path('add_favorite/<str:product_id>/', views.add_favorite,
         name='add_favorite'),
    path('del_favorite/<str:product_id>/', views.del_favorite,
         name='del_favorite'),
    path('legal_notice/', views.legal_notice, name='legal_notice'),
    path('mail_change/', views.mail_change, name='mail_change'),
]

purbeurre_project/purbeurre_project/urls.py
from django.conf import settings
from django.conf.urls import include, url

from django.contrib import admin
from django.urls import path

from bestproduct import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bestproduct.urls', namespace='besproduct')),
]

purbeurre_project/bestproduct/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    brand = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    nutrition_grade = models.CharField(max_length=1)
    picture = models.URLField()
    nutrition_image = models.URLField()
    url = models.URLField()


    def __str__(self):
        return self.name

class UserFavorite(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

purbeurre_project/bestproduct/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

"""We create a new class inheriting from UserCreationForm to which we had an email field,
it is this new class we call in the register view"""

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class ChangeMailForm(forms.Form):
	email = forms.EmailField(label='Your new email')

# https://docs.djangoproject.com/fr/2.1/ref/forms/api/#django.forms.Form.cleaned_data

purbeurre_project/bestproduct/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.contrib.auth.models import User
from .models import Product, UserFavorite
from .forms import UserRegisterForm, ChangeMailForm


def index(request):
    """ Display main page of website """
    return render(request, 'bestproduct/index.html')


def detail(request, product_id):
    """ Display information on one product """
    product = get_object_or_404(Product, pk=product_id)
    context = {
        'image': product.picture,
        'name': product.name,
        'product': product
    }
    return render(request, 'bestproduct/detail.html', context)


def replace(request):
    """
    Display list of products with better nutritive score than one searched
    by user
    """
    query = request.GET.get('query')

    # Use of icontains to increase the chance of finding a result
    products = Product.objects.filter(name__icontains=query)

    if len(products) > 0:
        choice = products[0]

        substitutes_list = Product.objects.filter(
                            category=choice.category,
                            nutrition_grade__lt=choice.nutrition_grade
                            ).order_by("nutrition_grade")[:6]
        
        context = {
            'id': choice.id,
            'name': choice.name,
            'image': choice.picture,
            'substitutes': substitutes_list,
        }

        return render(request, 'bestproduct/replace.html', context)

    else:
        # Warning for no product found and redirection to index
        messages.warning(request,
                         "Nous n'avons pas trouvé de produit correspondant")
        return redirect('bestproduct:index')


@login_required(login_url='/login')
def favorite(request):
    """ Display list of favorite products for connected user """
    user = request.user
    users_favorites_list = Product.objects.filter(
                                    userfavorite__user_name=user.id)
    if len(users_favorites_list) > 0:
        favorites_list = Product.objects.filter(pk__in=users_favorites_list).order_by('id')
    else:
        favorites_list = []

    page = request.GET.get('page', 1)
    paginator = Paginator(favorites_list, 6)
    try:
        favorites = paginator.page(page)
    except PageNotAnInteger:
        favorites = paginator.page(1)
    except EmptyPage:
        favorites = paginator.page(paginator.num_pages)

    return render(request, 'bestproduct/favorite.html',
                  {'favorites': favorites})


def register(request):
    """ Display of register page """
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request,
                             'Votre inscription est un succès, vous pouvez \
                             désormais vous connecter')
            return redirect('bestproduct:login')
    else:
        form = UserRegisterForm()

    return render(request, 'bestproduct/register.html', {'form': form})


@login_required(login_url='/login')
def profile(request):
    """ Display of profile page, only if user is logged in """
    user = request.user
    return render(request, 'bestproduct/profile.html', {'email':user.email})


@login_required(login_url='/login')
def add_favorite(request, product_id):
    """ Function for adding a favorite product from the replace page """
    try:
        UserFavorite.objects.get(user_name_id=request.user.id,
                                 product_id=(product_id))
        messages.warning(request, 'Ce produit est déjà dans vos favoris')
        return redirect(request.META.get('HTTP_REFERER'))
    except ObjectDoesNotExist:
        UserFavorite.objects.create(user_name_id=request.user.id,
                                    product_id=(product_id))
        messages.success(request, 'Le produit a été ajouté à vos favoris')
        return redirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='/login')
def del_favorite(request, product_id):
    try:
        UserFavorite.objects.get(user_name_id=request.user.id,
                                 product_id=(product_id))
        delete = UserFavorite.objects.get(user_name_id=request.user.id,
                                          product_id=(product_id))
        delete.delete()
        messages.success(request, 'Le produit a été retiré de vos favoris')
        #return redirect(request.META.get('HTTP_REFERER'))
        return redirect('bestproduct:favorite')
    except ObjectDoesNotExist:
        messages.warning(request, 'Le produit ne figure pas dans vos favoris')
        return redirect('bestproduct:favorite')


@login_required(login_url='/login')
def mail_change(request):
    """ Change of user's email adresse """

    if request.method == 'POST':
        form = ChangeMailForm(request.POST)
        if form.is_valid():
            change = User.objects.get(email=request.user.email)
            change.email = form.cleaned_data.get('email')
            change.save()

            # cleaned data : https://docs.djangoproject.com/fr/2.1/ref/forms/api/#django.forms.Form.cleaned_data

            messages.success(request,
                             'Votre adresse a été modifiée')
            return redirect('bestproduct:profile')
    else:
        form = ChangeMailForm()

    return render(request, 'bestproduct/mail_change.html', {'form': form})

def legal_notice(request):
    """ Display of Legal Notice page """
    return render(request, 'bestproduct/legal_notice.html')


"""
Web and documentation ressources :

Django messages :
-> https://docs.djangoproject.com/fr/2.2/ref/contrib/messages/

Django register view :
-> https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

Django Decorators :
-> https://docs.djangoproject.com/fr/2.2/topics/auth/default/

More info on the request.user :
-> https://stackoverflow.com/questions/17312831/what-does-request-user-refer-to-in-django
"""

purbeurre_project/bestproduct/templates/bestproduct/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" type="image/png" href="{% static 'bestproduct/img/logo_pb.png' %}" />

  <title> Pur Beurre </title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'bestproduct/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'bestproduct/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'bestproduct/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'bestproduct/css/creative.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <img id="logo" src="{% static 'bestproduct/img/logo_pb.png' %}" title="Pur Beurre" alt="Pur Beurre" />
      <a class="navbar-brand js-scroll-trigger" href="/">Pur Beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li>
              <form id="search-nav"  action="{% url 'bestproduct:replace' %}" method="get" accept-charset="utf-8">
                  <input type="text" name="query" id ="querynav" placeholder="Remplacer" required>
              </form>
          </li>

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a href="{% url 'bestproduct:profile' %}"> <i class="fas fa-user fa-2x mx-2" data-toggle="tooltip" title="Profil" ></i></a>
          </li>

          <li class="nav-item">
            <a href="{% url 'bestproduct:favorite' %}"> <i class="fas fa-carrot fa-2x mx-2" data-toggle="tooltip" title="Mes aliments" ></i></a>
          </li>

          <li class="nav-item">
            <a href="{% url 'bestproduct:logout' %}"> <i class="fas fa-sign-out-alt fa-2x mx-2" data-toggle="tooltip" title="Se déconnecter" ></i></a>
          </li>

          <!-- https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/ -->
          
          {% else %}

          <li class="nav-item">
            <a href="{% url 'bestproduct:register' %}"> <i class="fas fa-user-plus fa-2x mx-2" data-toggle="tooltip" title="Créer un compte" ></i></a>
          </li>

          <li class="nav-item">
            <a href="{% url 'bestproduct:login' %}"> <i class="fas fa-sign-in-alt fa-2x mx-2" data-toggle="tooltip" title="Se connecter" ></i></a>
          </li>
          {% endif %}


        </ul>
      </div>
    </div>
  </nav>

{% block content %}{% endblock %}

<!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 small mx-auto text-center">
          <a href="{% url 'bestproduct:legal_notice' %}">Mentions légales</a>
          <a id="cont" href="/#contact">Contact</a>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap bestproduct JavaScript -->
  <script src="{% static 'bestproduct/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'bestproduct/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'bestproduct/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'bestproduct/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'bestproduct/js/creative.min.js' %}"></script>

</body>

</html>

purbeurre_project/bestproduct/templates/bestproduct/detail.html
{% extends 'bestproduct/base.html' %}
{% block content %}
{% load static %}

<header class="smallheader text-center text-white d-flex" style="background-image: url({{ image }}) !important;">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <hr>
                <h2 class="text-uppercase">
                    <strong>{{ name }}</strong>
                </h2>
            </div>
        </div>
    </div>
</header>

<section>
  <div class="container">
    <div class="row" style="padding-top: 50px">
      <div class="col-sm-6 text-center">
        <img src="https://static.openfoodfacts.org/images/misc/nutriscore-{{ product.nutrition_grade }}.svg" alt="nutrition score {{ product.nutrition_grade }}" title="Nutri-score {{ product.nutrition_grade }}" />
      </div>
      <div class="col-sm-6 text-center">
        <img src="{{ product.nutrition_image}}" alt="nutrition 100g" title="Nutrition 100g" />
      </div>
    </div>
    <div class="row" style="padding-top: 50px">
      <div class="col-sm-12 text-center">
        <a href="{{ product.url }}" class="btn btn-primary btn-search">Voir la fiche d'Open Food Facts</a>
      </div>
    </div>
  </div>
</section>

{% endblock %}

purbeurre_project/bestproduct/templates/bestproduct/favorite.html
{% extends 'bestproduct/base.html' %}
{% block content %}
{% load static %}

<header class="smallheader text-center text-white d-flex" style="background-image: url({% static 'bestproduct/img/remy.png' %})">
  <div class="container my-auto">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <hr>
        <h2 class="text-uppercase">
          <strong> Mes aliments </strong>
        </h2>
      </div>
    </div>
  </div>
</header>

<section>
  <div class="container">
    <div class="col-md-18 text-center">

      {% if messages %}
          <div class="messages my-1">
              {% for message in messages %}
              <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
              {% endfor %}
          </div>
      {% endif %}
    
      <h4 class="section-heading padding-tb">La liste de vos aliments sauvegardés </h4>
      <div class="row">
        {% for favorite in favorites %}
          <div class="col-sm-4 text-center">
            <a href="/detail/{{ favorite.id }}">
              <img class="img-fluid img-product" src="{{ favorite.picture }}" alt="{{ favorite.name }}">
            </a>
            <div class="nutrigrade-icon">{{ favorite.nutrition_grade }}</div>
            <h5 class="padding-top"><a href="/detail/{{ favorite.id }}">{{ favorite.name }}</a></h5>
            
            {% if user.is_authenticated %}
              <form method="POST" action="{% url 'bestproduct:del_favorite' product_id=favorite.id %}">
                {% csrf_token %}
                <input class="btn btn-primary btn-l mt-50" type="submit" value="Supprimer" id="{{new_product.id}}">
              </form>
            {% endif %}
            
          </div>
          {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</section>

    <!-- https://simpleisbetterthancomplex.com/tutorial/2016/08/03/how-to-paginate-with-django.html -->
<section>
  <div class="container">
    {% if favorites.has_other_pages %}
      <ul class="pagination">
        {% if favorites.has_previous %}
          <li><a href="?page={{ favorites.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in favorites.paginator.page_range %}
          {% if favorites.number == i %}
            <li class="active mx-1"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li class="mx-1"><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if favorites.has_next %}
          <li><a href="?page={{ favorites.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}

  </div>
</section>
{% endblock %}

purbeurre_project/bestproduct/templates/bestproduct/index.html
{% extends 'bestproduct/base.html' %}
{% block content %}
{% load static %}

  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution <br> pour ceux que vous consommez tous les jours.</p>
          <form id="replace"  action="{% url 'bestproduct:replace' %}" method="get" accept-charset="utf-8">
                <input type="text" name="query" id ="query" placeholder="Produit à remplacer" required>
                <button type="submit" class="btn btn-primary btn-search">Remplacer</button>
          </form>

          {% if messages %}
          <div class="messages text-white-75 my-1">
              {% for message in messages %}
              <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
              {% endfor %}
          </div>
          {% endif %}

        </div>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section class="page-section bg-primary" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">Colette et Rémy</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.</p>
        </div>
      </div>
    </div>
    <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-9 text-center">
            <div class="mt-5 mx-auto">
              <img id="colette" src="{% static 'bestproduct/img/colette.jpg' %}" title="Colette" alt="Colette" />
              <h4 class="text-white mb-0 mt-2">Colette</h4>
            </div>
          </div>
          <div class="col-lg-6 col-md-9 text-center">
            <div class="mt-5 mx-auto">
              <img id="remy" src="{% static 'bestproduct/img/remy.png' %}" title="Rémy" alt="Rémy" />
              <h4 class="text-white mb-0 mt-2">Rémy</h4>
            </div>
          </div>
        </div>
    </div>
  </section>


  <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Contactez-nous !</h2>
          <hr class="divider my-4">
          <p class="text-muted mb-5">Ne soyez pas timides et contactez-nous, nous sommes à votre disposition par téléphone ou par mail.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+33 0 00 00 00 00</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <a class="d-block" href="mailto:mail@mail.com">mail@mail.com</a>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

purbeurre_project/bestproduct/templates/bestproduct/login.html
{% extends 'bestproduct/base.html' %}
{% block content %}
{% load static %}

<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Connexion</h1>
        <hr class="divider my-4">
      </div>

      <div class="container my-auto">

        <!-- messages : https://docs.djangoproject.com/fr/2.2/ref/contrib/messages/ -->
        {% if messages %}
        <ul class="messages text-white-75 my-1">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
            

        <form action="{% url 'bestproduct:login' %}" method="POST" name="login">
          {% csrf_token %}
          <fieldset class="form-group">
            <h3 class="mb-5 text-white-75 font-weight-light">Connectez-vous à votre compte Pur Beurre </h3>

          <div class="fieldWrapper text-white-75 font-weight-light">
            <label for="{{ form.username.id_for_label }}">Nom d'utilisateur</label>
            {{ form.username }}
          </div>

          <div class="fieldWrapper text-white-75 font-weight-light">
            <label for="{{ form.password.id_for_label }}">Mot de passe</label>
            {{ form.password }}
          </div>
          </fieldset>
          <div class="form-group">
            <button class="btn btn-primary btn-l mt-50 mb-3" type="submit">Connexion</button>
          </div>
        </form>
        
        <div>
          <p class="text-white-75 font-weight-lighter"> Vous n'avez pas de compte ? <a href="{% url 'bestproduct:register' %}">S'inscrire</a> </p>
        </div>

      </div>
      
    </div>
  </div>
</header>

{% endblock %}

purbeurre_project/bestproduct/templates/bestproduct/mail_change.html
{% extends 'bestproduct/base.html' %}
{% block content %}
{% load static %}

<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Modifier l'adresse mail</h1>
        <hr class="divider my-4">
      </div>

      <div class="container my-auto">
            

        <form action="{% url 'bestproduct:mail_change' %}" method="POST" name="mail_change">
          {% csrf_token %}
          <fieldset class="form-group">

          <div class="fieldWrapper text-white-75 font-weight-light">
            <label for="{{ form.email.id_for_label }}">Nouvelle adresse email</label>
            {{ form.email }}
            {% if form.email.errors %}
              {% for error in form.email.errors %}
                <p class="errorform">{{ error }}</p>
              {% endfor %}
            {% endif %}
          </div>

          <div class="form-group">
            <button class="btn btn-primary btn-l mt-50 mb-3" type="submit">Valider</button>
          </div>
        </form>

      </div>
      
    </div>
  </div>
</header>

{% endblock %}

purbeurre_project/bestproduct/templates/bestproduct/profile.html
{% extends 'bestproduct/base.html' %}
{% block content %}

  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">Ahoy {{ user.username }} !</h1>
          <hr class="divider my-4">
            <!-- messages : https://docs.djangoproject.com/fr/2.2/ref/contrib/messages/ -->
            {% if messages %}
            <ul class="messages text-white-75 my-1">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5"> {{ email }} </p>
        </div>
        <div class="col-lg-8 align-self-baseline">
          <a href="/mail_change/"><button class="btn btn-primary btn-l mt-50" value="fiche_produit"> Modifier l'adresse </button></a>
        </div>
      </div>
    </div>
  </header>

{% endblock %}

purbeurre_project/bestproduct/templates/bestproduct/register.html
{% extends 'bestproduct/base.html' %}
{% block content %}
{% load static %}

<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Inscription</h1>
        <hr class="divider my-4">
      </div>

      <div class="container my-auto">
        <form method="POST">
          {% csrf_token %}
            <fieldset class="form-group">
              <h3 class="mb-5 text-white-75 font-weight-light">Créez votre compte Pur Beurre</h3>
            </fieldset>

            <div class="fieldWrapper text-white-75 font-weight-light">
              <label for="{{ form.username.id_for_label }}">Nom d'utilisateur</label>
              {{ form.username }}
              {% if form.username.errors %}
                {% for error in form.username.errors %}
                  <p class="errorform">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>

            <div class="fieldWrapper text-white-75 font-weight-light">
              <label for="{{ form.email.id_for_label }}">Adresse email</label>
              {{ form.email }}
              {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <p class="errorform">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>

            <div class="fieldWrapper text-white-75 font-weight-light">
              <label for="{{ form.password.id_for_label }}">Mot de passe</label>
              {{ form.password1 }}
              {% if form.password1.errors %}
                {% for error in form.password1.errors %}
                  <p class="errorform">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>

            <div class="fieldWrapper text-white-75 font-weight-light mb-3">
              <label for="{{ form.password.id_for_label }}">Confirmation</label>
              {{ form.password2 }}
              {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                  <p class="errorform">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>
            
            <div class="form-group">
              <button class="btn btn-primary btn-l mt-50 mb-3" type="submit">Valider</button>
            </div>
        </form>
        
        <div>
          <p class="text-white-75 font-weight-lighter"> Vous avez déjà un compte ? <a href="{% url 'bestproduct:login' %}">Connexion</a> </p>
        </div>
      </div>

    </div>
  </div>
</header>

{% endblock content %}

purbeurre_project/bestproduct/templates/bestproduct/replace.html
{% extends 'bestproduct/base.html' %}
{% block content %}
{% load static %}

<header class="smallheader text-center text-white d-flex" style="background-image: url({{ image }}) !important;">
  <div class="container my-auto">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <hr>
        <h2 class="text-uppercase">
          <strong>{{ name }}</strong>
        </h2>
      </div>
    </div>
    <a href="/detail/{{ id }}"><button class="btn btn-primary btn-l mt-50" value="fiche_produit"> Fiche produit</button></a>
  </div>
</header>

<section>
  <div class="container">
    <div class="col-md-18 text-center">

    {% if messages %}
        <div class="messages my-1">
            {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}


      <h4 class="section-heading padding-tb">Vous pouvez remplacer cet aliment par : </h4>
      <div class="row">
        {% for substitute in substitutes %}
          <div class="col-sm-4 text-center">
            <a href="/detail/{{ substitute.id }}">
              <img class="img-fluid img-product" src="{{ substitute.picture }}" alt="{{ substitute.name }}">
            </a>
            <div class="nutrigrade-icon">{{ substitute.nutrition_grade }}</div>
            <h5 class="padding-top"><a href="/detail/{{ substitute.id }}">{{ substitute.name }}</a></h5>

            {% if user.is_authenticated %}
              <form method="POST" action="{% url 'bestproduct:add_favorite' product_id=substitute.id %}">
                {% csrf_token %}

                <input class="btn btn-primary btn-l mt-50" type="submit" value="Sauvegarder" id="{{new_product.id}}">
              </form>
            {% endif %}

          </div>
          {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</section>

{% endblock %}